
package com.shinfo.ecm.ebs.webService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-15T10:35:46.655+08:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "ParseException", targetNamespace = "http://webService.ebs.ecm.shinfo.com/")
public class ParseException_Exception extends Exception {
    
    private com.shinfo.ecm.ebs.webService.ParseException parseException;

    public ParseException_Exception() {
        super();
    }
    
    public ParseException_Exception(String message) {
        super(message);
    }
    
    public ParseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ParseException_Exception(String message, com.shinfo.ecm.ebs.webService.ParseException parseException) {
        super(message);
        this.parseException = parseException;
    }

    public ParseException_Exception(String message, com.shinfo.ecm.ebs.webService.ParseException parseException, Throwable cause) {
        super(message, cause);
        this.parseException = parseException;
    }

    public com.shinfo.ecm.ebs.webService.ParseException getFaultInfo() {
        return this.parseException;
    }
}
