package com.shinfo.ecm.ebs.webService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-19T15:36:53.795+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.shenhuagroup.com.cn/ZAOJIA", name = "SI_wbsTemplateWS_getWbsTemplateList_Syn_Out")
@XmlSeeAlso({ObjectFactory.class})
public interface SIWbsTemplateWSGetWbsTemplateListSynOut {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWbsTemplateList", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetWbsTemplateList")
    @WebMethod(action = "http://sap.com/xi/WebService/soap1.1")
    @ResponseWrapper(localName = "getWbsTemplateListResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetWbsTemplateListResponse")
    public java.lang.String getWbsTemplateList();
}
