
package com.shinfo.ecm.ebs.webService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-19T15:49:26.891+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class SIWbsTemplateWSImportWSExtimateDetailsSynOut_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.shenhuagroup.com.cn/ZAOJIA", "SI_wbsTemplateWS_importWSExtimateDetails_Syn_OutService");

    private SIWbsTemplateWSImportWSExtimateDetailsSynOut_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWbsTemplateWSImportWSExtimateDetailsSynOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWbsTemplateWSImportWSExtimateDetailsSynOutService ss = new SIWbsTemplateWSImportWSExtimateDetailsSynOutService(wsdlURL, SERVICE_NAME);
        SIWbsTemplateWSImportWSExtimateDetailsSynOut port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siWbsTemplateWSImportWSExtimateDetailsSynOut...");
        com.shinfo.ecm.ebs.webService.ImportWSExtimateDetails _siWbsTemplateWSImportWSExtimateDetailsSynOut_parameters = null;
        com.shinfo.ecm.ebs.webService.ImportWSExtimateDetailsResponse _siWbsTemplateWSImportWSExtimateDetailsSynOut__return = port.siWbsTemplateWSImportWSExtimateDetailsSynOut(_siWbsTemplateWSImportWSExtimateDetailsSynOut_parameters);
        System.out.println("siWbsTemplateWSImportWSExtimateDetailsSynOut.result=" + _siWbsTemplateWSImportWSExtimateDetailsSynOut__return);


        }

        System.exit(0);
    }

}
