package com.shinfo.ecm.ebs.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-15T10:35:46.683+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://webService.ebs.ecm.shinfo.com/", name = "WbsTemplateServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface WbsTemplateServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importWSAuditItemAndOpinons", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSAuditItemAndOpinons")
    @WebMethod
    @ResponseWrapper(localName = "importWSAuditItemAndOpinonsResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSAuditItemAndOpinonsResponse")
    public int importWSAuditItemAndOpinons(
        @WebParam(name = "auditItemList", targetNamespace = "")
        java.lang.String auditItemList,
        @WebParam(name = "subjId", targetNamespace = "")
        java.lang.String subjId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp
    ) throws ParseException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWbsTemplateNodesByIndustryTypeAndDisciplineType", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetWbsTemplateNodesByIndustryTypeAndDisciplineType")
    @WebMethod
    @ResponseWrapper(localName = "getWbsTemplateNodesByIndustryTypeAndDisciplineTypeResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetWbsTemplateNodesByIndustryTypeAndDisciplineTypeResponse")
    public java.lang.String getWbsTemplateNodesByIndustryTypeAndDisciplineType(
        @WebParam(name = "industryType", targetNamespace = "")
        java.lang.String industryType,
        @WebParam(name = "disciplineType", targetNamespace = "")
        java.lang.String disciplineType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importWSExtimateDetails", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSExtimateDetails")
    @WebMethod
    @ResponseWrapper(localName = "importWSExtimateDetailsResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSExtimateDetailsResponse")
    public int importWSExtimateDetails(
        @WebParam(name = "extimateList", targetNamespace = "")
        java.lang.String extimateList,
        @WebParam(name = "subjId", targetNamespace = "")
        java.lang.String subjId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "orderNum", targetNamespace = "")
        java.lang.Integer orderNum,
        @WebParam(name = "isTheLast", targetNamespace = "")
        java.lang.String isTheLast
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importRailwayJL", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportRailwayJL")
    @WebMethod
    @ResponseWrapper(localName = "importRailwayJLResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportRailwayJLResponse")
    public int importRailwayJL(
        @WebParam(name = "railwayXml", targetNamespace = "")
        java.lang.String railwayXml,
        @WebParam(name = "proId", targetNamespace = "")
        java.lang.String proId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "railwayId", targetNamespace = "")
        java.lang.String railwayId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWbsTemplateList", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetWbsTemplateList")
    @WebMethod
    @ResponseWrapper(localName = "getWbsTemplateListResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetWbsTemplateListResponse")
    public java.lang.String getWbsTemplateList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importElectricPowerOpinons", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportElectricPowerOpinons")
    @WebMethod
    @ResponseWrapper(localName = "importElectricPowerOpinonsResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportElectricPowerOpinonsResponse")
    public int importElectricPowerOpinons(
        @WebParam(name = "electricItemList", targetNamespace = "")
        java.lang.String electricItemList,
        @WebParam(name = "subjId", targetNamespace = "")
        java.lang.String subjId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "orderNum", targetNamespace = "")
        java.lang.Integer orderNum,
        @WebParam(name = "isTheLast", targetNamespace = "")
        java.lang.String isTheLast
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubProjectList", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetSubProjectList")
    @WebMethod
    @ResponseWrapper(localName = "getSubProjectListResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.GetSubProjectListResponse")
    public java.lang.String getSubProjectList(
        @WebParam(name = "projName", targetNamespace = "")
        java.lang.String projName
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importRailway", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportRailway")
    @WebMethod
    @ResponseWrapper(localName = "importRailwayResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportRailwayResponse")
    public int importRailway(
        @WebParam(name = "railwayXml", targetNamespace = "")
        java.lang.String railwayXml,
        @WebParam(name = "proId", targetNamespace = "")
        java.lang.String proId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "railwayId", targetNamespace = "")
        java.lang.String railwayId,
        @WebParam(name = "isSupplement", targetNamespace = "")
        java.lang.String isSupplement,
        @WebParam(name = "auditItemJson", targetNamespace = "")
        java.lang.String auditItemJson
    ) throws ParseException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importWSSettlementAndDetails", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSSettlementAndDetails")
    @WebMethod
    @ResponseWrapper(localName = "importWSSettlementAndDetailsResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSSettlementAndDetailsResponse")
    public int importWSSettlementAndDetails(
        @WebParam(name = "settlementList", targetNamespace = "")
        java.lang.String settlementList,
        @WebParam(name = "subjId", targetNamespace = "")
        java.lang.String subjId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "orderNum", targetNamespace = "")
        java.lang.Integer orderNum,
        @WebParam(name = "isTheLast", targetNamespace = "")
        java.lang.String isTheLast
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "importWSBudgetAndDetails", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSBudgetAndDetails")
    @WebMethod
    @ResponseWrapper(localName = "importWSBudgetAndDetailsResponse", targetNamespace = "http://webService.ebs.ecm.shinfo.com/", className = "com.shinfo.ecm.ebs.webService.ImportWSBudgetAndDetailsResponse")
    public int importWSBudgetAndDetails(
        @WebParam(name = "budgetList", targetNamespace = "")
        java.lang.String budgetList,
        @WebParam(name = "subjId", targetNamespace = "")
        java.lang.String subjId,
        @WebParam(name = "timeStamp", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar timeStamp,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.String type,
        @WebParam(name = "orderNum", targetNamespace = "")
        java.lang.Integer orderNum,
        @WebParam(name = "isTheLast", targetNamespace = "")
        java.lang.String isTheLast
    );
}
