package com.shinfo.ecm.ebs.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-15T10:35:46.695+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "WbsTemplateServiceImplService", 
                  wsdlLocation = "file:/E:/workspace/idea_2014/gradle-kotlin/src/main/java/com/shinfo/ecm/ebs/webService/wbsTemplateWSService.wsdl",
                  targetNamespace = "http://webService.ebs.ecm.shinfo.com/") 
public class WbsTemplateServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.ebs.ecm.shinfo.com/", "WbsTemplateServiceImplService");
    public final static QName WbsTemplateServiceImplPort = new QName("http://webService.ebs.ecm.shinfo.com/", "WbsTemplateServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/workspace/idea_2014/gradle-kotlin/src/main/java/com/shinfo/ecm/ebs/webService/wbsTemplateWSService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WbsTemplateServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/workspace/idea_2014/gradle-kotlin/src/main/java/com/shinfo/ecm/ebs/webService/wbsTemplateWSService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WbsTemplateServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WbsTemplateServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WbsTemplateServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WbsTemplateServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WbsTemplateServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WbsTemplateServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WbsTemplateServiceImpl
     */
    @WebEndpoint(name = "WbsTemplateServiceImplPort")
    public WbsTemplateServiceImpl getWbsTemplateServiceImplPort() {
        return super.getPort(WbsTemplateServiceImplPort, WbsTemplateServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WbsTemplateServiceImpl
     */
    @WebEndpoint(name = "WbsTemplateServiceImplPort")
    public WbsTemplateServiceImpl getWbsTemplateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WbsTemplateServiceImplPort, WbsTemplateServiceImpl.class, features);
    }

}
