
package com.shinfo.ecm.ebs.webService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-15T10:35:46.581+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class WbsTemplateServiceImpl_WbsTemplateServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webService.ebs.ecm.shinfo.com/", "WbsTemplateServiceImplService");

    private WbsTemplateServiceImpl_WbsTemplateServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WbsTemplateServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WbsTemplateServiceImplService ss = new WbsTemplateServiceImplService(wsdlURL, SERVICE_NAME);
        WbsTemplateServiceImpl port = ss.getWbsTemplateServiceImplPort();  
        
        {
        System.out.println("Invoking importWSAuditItemAndOpinons...");
        java.lang.String _importWSAuditItemAndOpinons_auditItemList = "";
        java.lang.String _importWSAuditItemAndOpinons_subjId = "";
        javax.xml.datatype.XMLGregorianCalendar _importWSAuditItemAndOpinons_timeStamp = null;
        try {
            int _importWSAuditItemAndOpinons__return = port.importWSAuditItemAndOpinons(_importWSAuditItemAndOpinons_auditItemList, _importWSAuditItemAndOpinons_subjId, _importWSAuditItemAndOpinons_timeStamp);
            System.out.println("importWSAuditItemAndOpinons.result=" + _importWSAuditItemAndOpinons__return);

        } catch (ParseException_Exception e) { 
            System.out.println("Expected exception: ParseException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getWbsTemplateNodesByIndustryTypeAndDisciplineType...");
        java.lang.String _getWbsTemplateNodesByIndustryTypeAndDisciplineType_industryType = "";
        java.lang.String _getWbsTemplateNodesByIndustryTypeAndDisciplineType_disciplineType = "";
        java.lang.String _getWbsTemplateNodesByIndustryTypeAndDisciplineType__return = port.getWbsTemplateNodesByIndustryTypeAndDisciplineType(_getWbsTemplateNodesByIndustryTypeAndDisciplineType_industryType, _getWbsTemplateNodesByIndustryTypeAndDisciplineType_disciplineType);
        System.out.println("getWbsTemplateNodesByIndustryTypeAndDisciplineType.result=" + _getWbsTemplateNodesByIndustryTypeAndDisciplineType__return);


        }
        {
        System.out.println("Invoking importWSExtimateDetails...");
        java.lang.String _importWSExtimateDetails_extimateList = "";
        java.lang.String _importWSExtimateDetails_subjId = "";
        javax.xml.datatype.XMLGregorianCalendar _importWSExtimateDetails_timeStamp = null;
        java.lang.String _importWSExtimateDetails_type = "";
        java.lang.Integer _importWSExtimateDetails_orderNum = null;
        java.lang.String _importWSExtimateDetails_isTheLast = "";
        int _importWSExtimateDetails__return = port.importWSExtimateDetails(_importWSExtimateDetails_extimateList, _importWSExtimateDetails_subjId, _importWSExtimateDetails_timeStamp, _importWSExtimateDetails_type, _importWSExtimateDetails_orderNum, _importWSExtimateDetails_isTheLast);
        System.out.println("importWSExtimateDetails.result=" + _importWSExtimateDetails__return);


        }
        {
        System.out.println("Invoking importRailwayJL...");
        java.lang.String _importRailwayJL_railwayXml = "";
        java.lang.String _importRailwayJL_proId = "";
        javax.xml.datatype.XMLGregorianCalendar _importRailwayJL_timeStamp = null;
        java.lang.String _importRailwayJL_railwayId = "";
        int _importRailwayJL__return = port.importRailwayJL(_importRailwayJL_railwayXml, _importRailwayJL_proId, _importRailwayJL_timeStamp, _importRailwayJL_railwayId);
        System.out.println("importRailwayJL.result=" + _importRailwayJL__return);


        }
        {
        System.out.println("Invoking getWbsTemplateList...");
        java.lang.String _getWbsTemplateList__return = port.getWbsTemplateList();
        System.out.println("getWbsTemplateList.result=" + _getWbsTemplateList__return);


        }
        {
        System.out.println("Invoking importElectricPowerOpinons...");
        java.lang.String _importElectricPowerOpinons_electricItemList = "";
        java.lang.String _importElectricPowerOpinons_subjId = "";
        javax.xml.datatype.XMLGregorianCalendar _importElectricPowerOpinons_timeStamp = null;
        java.lang.String _importElectricPowerOpinons_type = "";
        java.lang.Integer _importElectricPowerOpinons_orderNum = null;
        java.lang.String _importElectricPowerOpinons_isTheLast = "";
        int _importElectricPowerOpinons__return = port.importElectricPowerOpinons(_importElectricPowerOpinons_electricItemList, _importElectricPowerOpinons_subjId, _importElectricPowerOpinons_timeStamp, _importElectricPowerOpinons_type, _importElectricPowerOpinons_orderNum, _importElectricPowerOpinons_isTheLast);
        System.out.println("importElectricPowerOpinons.result=" + _importElectricPowerOpinons__return);


        }
        {
        System.out.println("Invoking getSubProjectList...");
        java.lang.String _getSubProjectList_projName = "";
        java.lang.String _getSubProjectList__return = port.getSubProjectList(_getSubProjectList_projName);
        System.out.println("getSubProjectList.result=" + _getSubProjectList__return);


        }
        {
        System.out.println("Invoking importRailway...");
        java.lang.String _importRailway_railwayXml = "";
        java.lang.String _importRailway_proId = "";
        javax.xml.datatype.XMLGregorianCalendar _importRailway_timeStamp = null;
        java.lang.String _importRailway_railwayId = "";
        java.lang.String _importRailway_isSupplement = "";
        java.lang.String _importRailway_auditItemJson = "";
        try {
            int _importRailway__return = port.importRailway(_importRailway_railwayXml, _importRailway_proId, _importRailway_timeStamp, _importRailway_railwayId, _importRailway_isSupplement, _importRailway_auditItemJson);
            System.out.println("importRailway.result=" + _importRailway__return);

        } catch (ParseException_Exception e) { 
            System.out.println("Expected exception: ParseException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking importWSSettlementAndDetails...");
        java.lang.String _importWSSettlementAndDetails_settlementList = "";
        java.lang.String _importWSSettlementAndDetails_subjId = "";
        javax.xml.datatype.XMLGregorianCalendar _importWSSettlementAndDetails_timeStamp = null;
        java.lang.String _importWSSettlementAndDetails_type = "";
        java.lang.Integer _importWSSettlementAndDetails_orderNum = null;
        java.lang.String _importWSSettlementAndDetails_isTheLast = "";
        int _importWSSettlementAndDetails__return = port.importWSSettlementAndDetails(_importWSSettlementAndDetails_settlementList, _importWSSettlementAndDetails_subjId, _importWSSettlementAndDetails_timeStamp, _importWSSettlementAndDetails_type, _importWSSettlementAndDetails_orderNum, _importWSSettlementAndDetails_isTheLast);
        System.out.println("importWSSettlementAndDetails.result=" + _importWSSettlementAndDetails__return);


        }
        {
        System.out.println("Invoking importWSBudgetAndDetails...");
        java.lang.String _importWSBudgetAndDetails_budgetList = "";
        java.lang.String _importWSBudgetAndDetails_subjId = "";
        javax.xml.datatype.XMLGregorianCalendar _importWSBudgetAndDetails_timeStamp = null;
        java.lang.String _importWSBudgetAndDetails_type = "";
        java.lang.Integer _importWSBudgetAndDetails_orderNum = null;
        java.lang.String _importWSBudgetAndDetails_isTheLast = "";
        int _importWSBudgetAndDetails__return = port.importWSBudgetAndDetails(_importWSBudgetAndDetails_budgetList, _importWSBudgetAndDetails_subjId, _importWSBudgetAndDetails_timeStamp, _importWSBudgetAndDetails_type, _importWSBudgetAndDetails_orderNum, _importWSBudgetAndDetails_isTheLast);
        System.out.println("importWSBudgetAndDetails.result=" + _importWSBudgetAndDetails__return);


        }

        System.exit(0);
    }

}
