
package com.itspub.demo.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-14T19:58:01.814+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class IDemoWebService_DemoWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.demo.itspub.com/", "DemoWebService");

    private IDemoWebService_DemoWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DemoWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DemoWebService ss = new DemoWebService(wsdlURL, SERVICE_NAME);
        IDemoWebService port = ss.getDemoWebServicePort();  
        
        {
        System.out.println("Invoking sayHelloWorld...");
        java.lang.String _sayHelloWorld__return = port.sayHelloWorld();
        System.out.println("sayHelloWorld.result=" + _sayHelloWorld__return);


        }

        System.exit(0);
    }

}
