package com.itspub.demo.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-14T19:58:01.860+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://ws.demo.itspub.com/", name = "IDemoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDemoWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://ws.demo.itspub.com/", className = "com.itspub.demo.ws.SayHelloWorld")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://ws.demo.itspub.com/", className = "com.itspub.demo.ws.SayHelloWorldResponse")
    public java.lang.String sayHelloWorld();
}
